### ISSUE TITLE
License file regex

### ISSUE THREAD

**Issue by m0Ray** [upciti/wheel2deb#48]
Line 30 of _wheel2deb/pydist.py indicates:
`    LICENSE_RE = re.compile(r"license", re.IGNORECASE)`
This leads to situation when every file with letters "license" in its path is treated as license.
As an example: PySide6-Essentials wheel contains directory "examples/widgets/dialogs/licensewizard" and a lot of files (including binaries such as PNG) under it. All of them are shown as licenses.
Then at line 201-202 of _wheel2deb/debian.py it tries to read PNG file and decode as UTF-8. Crash-bang...

I suggest to change LICENSE_RE for example to:
`re.compile(r"(^|[^\w])license(\..*)?$", re.IGNORECASE)`
It catches all variations of "license" and "dir/license.ext", but not "license/notreally" and "notalicense".

**Comment by fyhertz** [comment]
Mmm indeed, I really don't have time work on this project right now, but If you make a PR I would be happy to merge it!
