### ISSUE TITLE
Wildcard * in dependency breaks conversion

### ISSUE THREAD

**Issue by jm-imca** [upciti/wheel2deb#5]
Hi guys,
thanks for this very helpful tool! I just started to work with it to allow offline installations of python packages on an embedded linux control device.
I am experiencing a crash if the wheel file contains a wildcard in a dependency string , e.g. `==7.*`
This happend to me then I tried to convert uvicorn. The crash happend in line 151 of depends.py because the parsed.release variable is `None `in this case.
Because my Python is not good enough to fix this on my own, I rather leave it up to someone with more experience. 
I was working with `wheel2deb-0.5.7` and tried to convert `uvicorn-0.11.1`. The breaking dependencies strings are `python3-click (click==7.*) `and` python3-websockets (websockets==8.*)`.

**Comment by fyhertz** [comment]
Thank you for your feedback :) I will look into it

**Comment by smartsammler** [comment]
Thank you this software and for this fix.
Can you release a new version to PyPI, so one can easily benefit from this fix? That would be very kind.
