### ISSUE TITLE
whl does not support python 3.1

### ISSUE THREAD

**Issue by AndPim4912** [upciti/wheel2deb#57]
wheel2deb
 --> Unpacking 1 wheels
     wheel2deb-0.5.8-py3-none-any.whl does not support python 3.1
     
Warnings: 1. Errors: 0. Elapsed: 0.04s.

python3 --version
Python 3.11.2

attrs==23.1.0
colorama==0.4.6
dirsync==2.2.5
Jinja2==3.1.2
MarkupSafe==2.1.3
packaging==23.1
pkginfo==1.9.6
PyYAML==6.0.1
six==1.16.0
wheel2deb==0.5.8

**Comment by fyhertz** [comment]
Make sure you are running the latest release of wheel2deb !
