### ISSUE TITLE
Problem with some pip wheel

### ISSUE THREAD

**Issue by nicko27** [upciti/wheel2deb#58]
Hi, 
If you want to convert onnxruntime or onnxruntime it failed.

**Comment by fyhertz** [comment]
Re-try with the latest release, I had to do just that today and the conversion succeeds on bookworm/arm64 !

**Comment by nicko27** [comment]
Tried this morning with wheel2deb 0.9.5 and I've got this error:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /media/nico/Drive/laraTest/myvenv/lib/python3.10/site-packages/wheel2deb/cli.py:166 in default   │
│                                                                                                  │
│   163 │   with print_summary_and_exit():                                                         │
│   164 │   │   settings = load_configuration(configuration_path)                                  │
│   165 │   │   wheel_paths = filter_wheels(search_paths, include_wheels, exclude_wheels)          │
│ ❱ 166 │   │   packages = convert_wheels(settings, output_directory, wheel_paths)                 │
│   167 │   │   build_packages([p.root for p in packages], workers_count, force_build)             │
│   168                                                                                            │
│   169                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ configuration_path = None                                                                    │ │
│ │     exclude_wheels = None                                                                    │ │
│ │        force_build = False                                                                   │ │
│ │     include_wheels = None                                                                    │ │
│ │   output_directory = PosixPath('output')                                                     │ │
│ │       search_paths = [PosixPath('.')]                                                        │ │
│ │           settings = Settings(                                                               │ │
│ │                      │   config={},                                                          │ │
│ │                      │   default_ctx=Context(                                                │ │
│ │                      │   │   maintainer_name='wheel2deb',                                    │ │
│ │                      │   │   maintainer_email='wheel2deb@upciti.com',                        │ │
│ │                      │   │   distribution='unstable',                                        │ │
│ │                      │   │   python_version=Version(major=3, minor=10, micro=12),            │ │
│ │                      │   │   platform_machine='x86_64',                                      │ │
│ │                      │   │   arch='',                                                        │ │
│ │                      │   │   ignore_entry_points=False,                                      │ │
│ │                      │   │   ignore_upstream_versions=False,                                 │ │
│ │                      │   │   ignore_requirements=[],                                         │ │
│ │                      │   │   ignore_specifiers=[],                                           │ │
│ │                      │   │   extra='',                                                       │ │
│ │                      │   │   map={},                                                         │ │
│ │                      │   │   depends=[],                                                     │ │
│ │                      │   │   conflicts=[],                                                   │ │
│ │                      │   │   provides=[],                                                    │ │
│ │                      │   │   revision='1',                                                   │ │
│ │                      │   │   epoch=0,                                                        │ │
│ │                      │   │                                                                   │ │
│ │                      version_template='{epoch}:{upstream_version}-{revision}~w2d{w2d_versio… │ │
│ │                      │   │   extended_desc='This package was generated by wheel2deb v0'      │ │
│ │                      │   )                                                                   │ │
│ │                      )                                                                       │ │
│ │            verbose = None                                                                    │ │
│ │        wheel_paths = [                                                                       │ │
│ │                      │                                                                       │ │
│ │                      PosixPath('Brotli-1.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x8… │ │
│ │                      │   PosixPath('HyperPyYAML-1.2.2-py3-none-any.whl'),                    │ │
│ │                      │   PosixPath('Mako-1.3.5-py3-none-any.whl'),                           │ │
│ │                      │   PosixPath('Markdown-3.6-py3-none-any.whl'),                         │ │
│ │                      │                                                                       │ │
│ │                      PosixPath('MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinu… │ │
│ │                      │                                                                       │ │
│ │                      PosixPath('PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux201… │ │
│ │                      │                                                                       │ │
│ │                      PosixPath('SQLAlchemy-2.0.31-cp310-cp310-manylinux_2_17_x86_64.manylin… │ │
│ │                      │   PosixPath('SoundFile-0.10.3.post1-py2.py3-none-any.whl'),           │ │
│ │                      │   PosixPath('absl_py-2.1.0-py3-none-any.whl'),                        │ │
│ │                      │                                                                       │ │
│ │                      PosixPath('aiohttp-3.9.5-cp310-cp310-manylinux_2_17_x86_64.manylinux20… │ │
│ │                      │   ... +114                                                            │ │
│ │                      ]                                                                       │ │
│ │      workers_count = 4                                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /media/nico/Drive/laraTest/myvenv/lib/python3.10/site-packages/wheel2deb/debian.py:341 in        │
│ convert_wheels                                                                                   │
│                                                                                                  │
│   338 │   for wheel in wheels:                                                                   │
│   339 │   │   logger.task(f"Converting wheel {wheel}")                                           │
│   340 │   │   ctx = settings.get_ctx(wheel.wheel_name)                                           │
│ ❱ 341 │   │   package = SourcePackage(ctx, wheel, output_directory, extras=wheels)               │
│   342 │   │   package.create()                                                                   │
│   343 │   │   packages.append(package)                                                           │
│   344                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              ctx = Context(                                                                  │ │
│ │                    │   maintainer_name='wheel2deb',                                          │ │
│ │                    │   maintainer_email='wheel2deb@upciti.com',                              │ │
│ │                    │   distribution='unstable',                                              │ │
│ │                    │   python_version=Version(major=3, minor=10, micro=12),                  │ │
│ │                    │   platform_machine='x86_64',                                            │ │
│ │                    │   arch='',                                                              │ │
│ │                    │   ignore_entry_points=False,                                            │ │
│ │                    │   ignore_upstream_versions=False,                                       │ │
│ │                    │   ignore_requirements=[],                                               │ │
│ │                    │   ignore_specifiers=[],                                                 │ │
│ │                    │   extra='',                                                             │ │
│ │                    │   map={},                                                               │ │
│ │                    │   depends=[],                                                           │ │
│ │                    │   conflicts=[],                                                         │ │
│ │                    │   provides=[],                                                          │ │
│ │                    │   revision='1',                                                         │ │
│ │                    │   epoch=0,                                                              │ │
│ │                    │                                                                         │ │
│ │                    version_template='{epoch}:{upstream_version}-{revision}~w2d{w2d_version[… │ │
│ │                    │   extended_desc='This package was generated by wheel2deb v0'            │ │
│ │                    )                                                                         │ │
│ │             file = PosixPath('zopfli-0.2.3-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_… │ │
│ │ output_directory = PosixPath('output')                                                       │ │
│ │          package = <wheel2deb.debian.SourcePackage object at 0x7d932965f1f0>                 │ │
│ │         packages = [                                                                         │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d932978d510>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d9329604d00>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d9329607e50>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d9329606020>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d93296068c0>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d93296045b0>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d9329606cb0>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d932978f010>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d932978e950>,            │ │
│ │                    │   <wheel2deb.debian.SourcePackage object at 0x7d932978e590>,            │ │
│ │                    │   ... +47                                                               │ │
│ │                    ]                                                                         │ │
│ │         settings = Settings(                                                                 │ │
│ │                    │   config={},                                                            │ │
│ │                    │   default_ctx=Context(                                                  │ │
│ │                    │   │   maintainer_name='wheel2deb',                                      │ │
│ │                    │   │   maintainer_email='wheel2deb@upciti.com',                          │ │
│ │                    │   │   distribution='unstable',                                          │ │
│ │                    │   │   python_version=Version(major=3, minor=10, micro=12),              │ │
│ │                    │   │   platform_machine='x86_64',                                        │ │
│ │                    │   │   arch='',                                                          │ │
│ │                    │   │   ignore_entry_points=False,                                        │ │
│ │                    │   │   ignore_upstream_versions=False,                                   │ │
│ │                    │   │   ignore_requirements=[],                                           │ │
│ │                    │   │   ignore_specifiers=[],                                             │ │
│ │                    │   │   extra='',                                                         │ │
│ │                    │   │   map={},                                                           │ │
│ │                    │   │   depends=[],                                                       │ │
│ │                    │   │   conflicts=[],                                                     │ │
│ │                    │   │   provides=[],                                                      │ │
│ │                    │   │   revision='1',                                                     │ │
│ │                    │   │   epoch=0,                                                          │ │
│ │                    │   │                                                                     │ │
│ │                    version_template='{epoch}:{upstream_version}-{revision}~w2d{w2d_version[… │ │
│ │                    │   │   extended_desc='This package was generated by wheel2deb v0'        │ │
│ │                    │   )                                                                     │ │
│ │                    )                                                                         │ │
│ │            wheel = onnxruntime-1.18.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_… │ │
│ │      wheel_paths = [                                                                         │ │
│ │                    │                                                                         │ │
│ │                    PosixPath('Brotli-1.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_… │ │
│ │                    │   PosixPath('HyperPyYAML-1.2.2-py3-none-any.whl'),                      │ │
│ │                    │   PosixPath('Mako-1.3.5-py3-none-any.whl'),                             │ │
│ │                    │   PosixPath('Markdown-3.6-py3-none-any.whl'),                           │ │
│ │                    │                                                                         │ │
│ │                    PosixPath('MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2… │ │
│ │                    │                                                                         │ │
│ │                    PosixPath('PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_… │ │
│ │                    │                                                                         │ │
│ │                    PosixPath('SQLAlchemy-2.0.31-cp310-cp310-manylinux_2_17_x86_64.manylinux… │ │
│ │                    │   PosixPath('SoundFile-0.10.3.post1-py2.py3-none-any.whl'),             │ │
│ │                    │   PosixPath('absl_py-2.1.0-py3-none-any.whl'),                          │ │
│ │                    │                                                                         │ │
│ │                    PosixPath('aiohttp-3.9.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014… │ │
│ │                    │   ... +114                                                              │ │
│ │                    ]                                                                         │ │
│ │           wheels = [                                                                         │ │
│ │                    │                                                                         │ │
│ │                    Brotli-1.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinu… │ │
│ │                    │   HyperPyYAML-1.2.2-py3-none-any.whl,                                   │ │
│ │                    │   Mako-1.3.5-py3-none-any.whl,                                          │ │
│ │                    │   Markdown-3.6-py3-none-any.whl,                                        │ │
│ │                    │                                                                         │ │
│ │                    MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.… │ │
│ │                    │                                                                         │ │
│ │                    PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl,  │ │
│ │                    │                                                                         │ │
│ │                    SQLAlchemy-2.0.31-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64… │ │
│ │                    │   SoundFile-0.10.3.post1-py2.py3-none-any.whl,                          │ │
│ │                    │   absl_py-2.1.0-py3-none-any.whl,                                       │ │
│ │                    │                                                                         │ │
│ │                    aiohttp-3.9.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, │ │
│ │                    │   ... +114                                                              │ │
│ │                    ]                                                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /media/nico/Drive/laraTest/myvenv/lib/python3.10/site-packages/wheel2deb/debian.py:113 in        │
│ __init__                                                                                         │
│                                                                                                  │
│   110 │   │   │   if vrange.min:                                                                 │
│   111 │   │   │   │   self.depends.append(f"{self.interpreter} (>= {vrange.min}~)")              │
│   112 │   │                                                                                      │
│ ❱ 113 │   │   deps, missing = search_python_deps(ctx, wheel, extras)                             │
│   114 │   │   self.depends.extend(deps)                                                          │
│   115 │   │   self.depends.extend(ctx.depends)                                                   │
│   116                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                  arch = 'amd64'                                                              │ │
│ │                   ctx = Context(                                                             │ │
│ │                         │   maintainer_name='wheel2deb',                                     │ │
│ │                         │   maintainer_email='wheel2deb@upciti.com',                         │ │
│ │                         │   distribution='unstable',                                         │ │
│ │                         │   python_version=Version(major=3, minor=10, micro=12),             │ │
│ │                         │   platform_machine='x86_64',                                       │ │
│ │                         │   arch='',                                                         │ │
│ │                         │   ignore_entry_points=False,                                       │ │
│ │                         │   ignore_upstream_versions=False,                                  │ │
│ │                         │   ignore_requirements=[],                                          │ │
│ │                         │   ignore_specifiers=[],                                            │ │
│ │                         │   extra='',                                                        │ │
│ │                         │   map={},                                                          │ │
│ │                         │   depends=[],                                                      │ │
│ │                         │   conflicts=[],                                                    │ │
│ │                         │   provides=[],                                                     │ │
│ │                         │   revision='1',                                                    │ │
│ │                         │   epoch=0,                                                         │ │
│ │                         │                                                                    │ │
│ │                         version_template='{epoch}:{upstream_version}-{revision}~w2d{w2d_ver… │ │
│ │                         │   extended_desc='This package was generated by wheel2deb v0'       │ │
│ │                         )                                                                    │ │
│ │                extras = [                                                                    │ │
│ │                         │                                                                    │ │
│ │                         Brotli-1.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.man… │ │
│ │                         │   HyperPyYAML-1.2.2-py3-none-any.whl,                              │ │
│ │                         │   Mako-1.3.5-py3-none-any.whl,                                     │ │
│ │                         │   Markdown-3.6-py3-none-any.whl,                                   │ │
│ │                         │                                                                    │ │
│ │                         MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x8… │ │
│ │                         │                                                                    │ │
│ │                         PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64… │ │
│ │                         │                                                                    │ │
│ │                         SQLAlchemy-2.0.31-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x… │ │
│ │                         │   SoundFile-0.10.3.post1-py2.py3-none-any.whl,                     │ │
│ │                         │   absl_py-2.1.0-py3-none-any.whl,                                  │ │
│ │                         │                                                                    │ │
│ │                         aiohttp-3.9.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_6… │ │
│ │                         │   ... +114                                                         │ │
│ │                         ]                                                                    │ │
│ │                output = PosixPath('output')                                                  │ │
│ │                  self = <wheel2deb.debian.SourcePackage object at 0x7d932965f580>            │ │
│ │ version_without_epoch = '1.18.1-1~w2d0'                                                      │ │
│ │                vrange = VersionRange(                                                        │ │
│ │                         │   min=Version(major=3, minor=10, micro=0),                         │ │
│ │                         │   max=Version(major=3, minor=11, micro=0)                          │ │
│ │                         )                                                                    │ │
│ │                 wheel = onnxruntime-1.18.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /media/nico/Drive/laraTest/myvenv/lib/python3.10/site-packages/wheel2deb/depends.py:140 in       │
│ search_python_deps                                                                               │
│                                                                                                  │
│   137 │   │                                                                                      │
│   138 │   │   version = None                                                                     │
│   139 │   │   for candidate in candidates[req.name]:                                             │
│ ❱ 140 │   │   │   if check(candidate):                                                           │
│   141 │   │   │   │   if (version and parse(candidate.version) < parse(version)) or not versio   │
│   142 │   │   │   │   │   version = candidate.version                                            │
│   143                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    candidate = Package(                                                                      │ │
│ │                │   name='python3-flatbuffers',                                               │ │
│ │                │   version='1.12.1~git20200711.33e2d80',                                     │ │
│ │                │   revision=None,                                                            │ │
│ │                │   epoch=None                                                                │ │
│ │                )                                                                             │ │
│ │   candidates = {                                                                             │ │
│ │                │   'packaging': [                                                            │ │
│ │                │   │   Package(                                                              │ │
│ │                │   │   │   name='python3-packaging',                                         │ │
│ │                │   │   │   version='21.3',                                                   │ │
│ │                │   │   │   revision='1',                                                     │ │
│ │                │   │   │   epoch=None                                                        │ │
│ │                │   │   ),                                                                    │ │
│ │                │   │   packaging-24.1-py3-none-any.whl                                       │ │
│ │                │   ],                                                                        │ │
│ │                │   'sympy': [                                                                │ │
│ │                │   │   Package(                                                              │ │
│ │                │   │   │   name='python3-sympy',                                             │ │
│ │                │   │   │   version='1.9',                                                    │ │
│ │                │   │   │   revision='1',                                                     │ │
│ │                │   │   │   epoch=None                                                        │ │
│ │                │   │   ),                                                                    │ │
│ │                │   │   sympy-1.13.1-py3-none-any.whl                                         │ │
│ │                │   ],                                                                        │ │
│ │                │   'numpy': [                                                                │ │
│ │                │   │   Package(                                                              │ │
│ │                │   │   │   name='python3-numpy',                                             │ │
│ │                │   │   │   version='1.21.5',                                                 │ │
│ │                │   │   │   revision='1ubuntu22.04.1',                                        │ │
│ │                │   │   │   epoch='1'                                                         │ │
│ │                │   │   ),                                                                    │ │
│ │                │   │                                                                         │ │
│ │                numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl       │ │
│ │                │   ],                                                                        │ │
│ │                │   'protobuf': [                                                             │ │
│ │                │   │   Package(                                                              │ │
│ │                │   │   │   name='python3-protobuf',                                          │ │
│ │                │   │   │   version='3.12.4',                                                 │ │
│ │                │   │   │   revision='1ubuntu7.22.04.1',                                      │ │
│ │                │   │   │   epoch=None                                                        │ │
│ │                │   │   ),                                                                    │ │
│ │                │   │                                                                         │ │
│ │                protobuf-3.20.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl    │ │
│ │                │   ],                                                                        │ │
│ │                │   'coloredlogs': [                                                          │ │
│ │                │   │   Package(                                                              │ │
│ │                │   │   │   name='python3-coloredlogs',                                       │ │
│ │                │   │   │   version='7.3',                                                    │ │
│ │                │   │   │   revision='2',                                                     │ │
│ │                │   │   │   epoch=None                                                        │ │
│ │                │   │   ),                                                                    │ │
│ │                │   │   coloredlogs-15.0.1-py2.py3-none-any.whl                               │ │
│ │                │   ],                                                                        │ │
│ │                │   'flatbuffers': [                                                          │ │
│ │                │   │   Package(                                                              │ │
│ │                │   │   │   name='python3-flatbuffers',                                       │ │
│ │                │   │   │   version='1.12.1~git20200711.33e2d80',                             │ │
│ │                │   │   │   revision=None,                                                    │ │
│ │                │   │   │   epoch=None                                                        │ │
│ │                │   │   ),                                                                    │ │
│ │                │   │   flatbuffers-24.3.25-py2.py3-none-any.whl                              │ │
│ │                │   ]                                                                         │ │
│ │                }                                                                             │ │
│ │        check = <function search_python_deps.<locals>.check at 0x7d9329650a60>                │ │
│ │          ctx = Context(                                                                      │ │
│ │                │   maintainer_name='wheel2deb',                                              │ │
│ │                │   maintainer_email='wheel2deb@upciti.com',                                  │ │
│ │                │   distribution='unstable',                                                  │ │
│ │                │   python_version=Version(major=3, minor=10, micro=12),                      │ │
│ │                │   platform_machine='x86_64',                                                │ │
│ │                │   arch='',                                                                  │ │
│ │                │   ignore_entry_points=False,                                                │ │
│ │                │   ignore_upstream_versions=False,                                           │ │
│ │                │   ignore_requirements=[],                                                   │ │
│ │                │   ignore_specifiers=[],                                                     │ │
│ │                │   extra='',                                                                 │ │
│ │                │   map={},                                                                   │ │
│ │                │   depends=[],                                                               │ │
│ │                │   conflicts=[],                                                             │ │
│ │                │   provides=[],                                                              │ │
│ │                │   revision='1',                                                             │ │
│ │                │   epoch=0,                                                                  │ │
│ │                │                                                                             │ │
│ │                version_template='{epoch}:{upstream_version}-{revision}~w2d{w2d_version[0]}', │ │
│ │                │   extended_desc='This package was generated by wheel2deb v0'                │ │
│ │                )                                                                             │ │
│ │  debian_deps = [                                                                             │ │
│ │                │   'python3-packaging',                                                      │ │
│ │                │   'python3-sympy',                                                          │ │
│ │                │   'python3-numpy (<< 2.0)',                                                 │ │
│ │                │   'python3-numpy (>= 1.21.6)',                                              │ │
│ │                │   'python3-protobuf',                                                       │ │
│ │                │   'python3-coloredlogs'                                                     │ │
│ │                ]                                                                             │ │
│ │     debnames = [                                                                             │ │
│ │                │   'python3-packaging',                                                      │ │
│ │                │   'python3-sympy',                                                          │ │
│ │                │   'python3-numpy',                                                          │ │
│ │                │   'python3-protobuf',                                                       │ │
│ │                │   'python3-coloredlogs',                                                    │ │
│ │                │   'python3-flatbuffers'                                                     │ │
│ │                ]                                                                             │ │
│ │          dep = 'python3-numpy (>= 1.21.6)'                                                   │ │
│ │        extra = zopfli-0.2.3-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl       │ │
│ │       extras = [                                                                             │ │
│ │                │                                                                             │ │
│ │                Brotli-1.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_… │ │
│ │                │   HyperPyYAML-1.2.2-py3-none-any.whl,                                       │ │
│ │                │   Mako-1.3.5-py3-none-any.whl,                                              │ │
│ │                │   Markdown-3.6-py3-none-any.whl,                                            │ │
│ │                │                                                                             │ │
│ │                MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl,  │ │
│ │                │   PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl,  │ │
│ │                │                                                                             │ │
│ │                SQLAlchemy-2.0.31-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, │ │
│ │                │   SoundFile-0.10.3.post1-py2.py3-none-any.whl,                              │ │
│ │                │   absl_py-2.1.0-py3-none-any.whl,                                           │ │
│ │                │   aiohttp-3.9.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, │ │
│ │                │   ... +114                                                                  │ │
│ │                ]                                                                             │ │
│ │  is_required = <function search_python_deps.<locals>.is_required at 0x7d93298f9cf0>          │ │
│ │ missing_deps = []                                                                            │ │
│ │         pdep = 'python3-flatbuffers'                                                         │ │
│ │          req = <Requirement('flatbuffers')>                                                  │ │
│ │ requirements = [                                                                             │ │
│ │                │   <Requirement('packaging')>,                                               │ │
│ │                │   <Requirement('sympy')>,                                                   │ │
│ │                │   <Requirement('numpy<2.0,>=1.21.6')>,                                      │ │
│ │                │   <Requirement('protobuf')>,                                                │ │
│ │                │   <Requirement('coloredlogs')>,                                             │ │
│ │                │   <Requirement('flatbuffers')>                                              │ │
│ │                ]                                                                             │ │
│ │          res = Package(                                                                      │ │
│ │                │   name='python3-flatbuffers',                                               │ │
│ │                │   version='1.12.1~git20200711.33e2d80',                                     │ │
│ │                │   revision=None,                                                            │ │
│ │                │   epoch=None                                                                │ │
│ │                )                                                                             │ │
│ │      results = <generator object search_packages at 0x7d93295231b0>                          │ │
│ │    specifier = <Specifier('>=1.21.6')>                                                       │ │
│ │      version = None                                                                          │ │
│ │        wheel = onnxruntime-1.18.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.w… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /media/nico/Drive/laraTest/myvenv/lib/python3.10/site-packages/wheel2deb/depends.py:130 in check │
│                                                                                                  │
│   127 │   for pdep, req in zip(debnames, requirements):                                          │
│   128 │   │                                                                                      │
│   129 │   │   def check(x):                                                                      │
│ ❱ 130 │   │   │   if req.specifier.contains(x.version, prereleases=True):                        │
│   131 │   │   │   │   logger.info(f"{x} satisfies requirement {req}")                            │
│   132 │   │   │   else:                                                                          │
│   133 │   │   │   │   logger.warning(f"{x} does not satisfy requirement {req}")                  │
│                                                                                                  │
│ ╭──────────────────────────────────────── locals ─────────────────────────────────────────╮      │
│ │ ctx = Context(                                                                          │      │
│ │       │   maintainer_name='wheel2deb',                                                  │      │
│ │       │   maintainer_email='wheel2deb@upciti.com',                                      │      │
│ │       │   distribution='unstable',                                                      │      │
│ │       │   python_version=Version(major=3, minor=10, micro=12),                          │      │
│ │       │   platform_machine='x86_64',                                                    │      │
│ │       │   arch='',                                                                      │      │
│ │       │   ignore_entry_points=False,                                                    │      │
│ │       │   ignore_upstream_versions=False,                                               │      │
│ │       │   ignore_requirements=[],                                                       │      │
│ │       │   ignore_specifiers=[],                                                         │      │
│ │       │   extra='',                                                                     │      │
│ │       │   map={},                                                                       │      │
│ │       │   depends=[],                                                                   │      │
│ │       │   conflicts=[],                                                                 │      │
│ │       │   provides=[],                                                                  │      │
│ │       │   revision='1',                                                                 │      │
│ │       │   epoch=0,                                                                      │      │
│ │       │   version_template='{epoch}:{upstream_version}-{revision}~w2d{w2d_version[0]}', │      │
│ │       │   extended_desc='This package was generated by wheel2deb v0'                    │      │
│ │       )                                                                                 │      │
│ │ req = <Requirement('flatbuffers')>                                                      │      │
│ │   x = Package(                                                                          │      │
│ │       │   name='python3-flatbuffers',                                                   │      │
│ │       │   version='1.12.1~git20200711.33e2d80',                                         │      │
│ │       │   revision=None,                                                                │      │
│ │       │   epoch=None                                                                    │      │
│ │       )                                                                                 │      │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────╯      │
│                                                                                                  │
│ /media/nico/Drive/laraTest/myvenv/lib/python3.10/site-packages/packaging/specifiers.py:906 in    │
│ contains                                                                                         │
│                                                                                                  │
│    903 │   │   """                                                                               │
│    904 │   │   # Ensure that our item is a Version instance.                                     │
│    905 │   │   if not isinstance(item, Version):                                                 │
│ ❱  906 │   │   │   item = Version(item)                                                          │
│    907 │   │                                                                                     │
│    908 │   │   # Determine if we're forcing a prerelease or not, if we're not forcing            │
│    909 │   │   # one for this particular filter call, then we'll use whatever the                │
│                                                                                                  │
│ ╭────────────────── locals ──────────────────╮                                                   │
│ │   installed = None                         │                                                   │
│ │        item = '1.12.1~git20200711.33e2d80' │                                                   │
│ │ prereleases = True                         │                                                   │
│ │        self = <SpecifierSet('')>           │                                                   │
│ ╰────────────────────────────────────────────╯                                                   │
│                                                                                                  │
│ /media/nico/Drive/laraTest/myvenv/lib/python3.10/site-packages/packaging/version.py:202 in       │
│ __init__                                                                                         │
│                                                                                                  │
│   199 │   │   # Validate the version and parse it into pieces                                    │
│   200 │   │   match = self._regex.search(version)                                                │
│   201 │   │   if not match:                                                                      │
│ ❱ 202 │   │   │   raise InvalidVersion(f"Invalid version: '{version}'")                          │
│   203 │   │                                                                                      │
│   204 │   │   # Store the parsed out pieces of the version                                       │
│   205 │   │   self._version = _Version(                                                          │
│                                                                                                  │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                        │
│ │   match = None                                                        │                        │
│ │    self = <repr-error "'Version' object has no attribute '_version'"> │                        │
│ │ version = '1.12.1~git20200711.33e2d80'                                │                        │
│ ╰───────────────────────────────────────────────────────────────────────╯                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InvalidVersion: Invalid version: '1.12.1~git20200711.33e2d80'
